2025-01-07 01:18:32 ERROR auto_prep.preprocessing.scaling: Failed to transform ColumnScaler This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
Traceback (most recent call last):
  File "/Users/pawelp/Desktop/education/pw/automl/AutoPrep/auto_prep/preprocessing/scaling.py", line 94, in transform
    X_transformed[numerical_cols] = self.scaler.transform(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 513, in transform
    check_is_fitted(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1461, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
2025-01-07 01:18:32 ERROR auto_prep.preprocessing.scaling: Failed to transform ColumnScaler This RobustScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
Traceback (most recent call last):
  File "/Users/pawelp/Desktop/education/pw/automl/AutoPrep/auto_prep/preprocessing/scaling.py", line 94, in transform
    X_transformed[numerical_cols] = self.scaler.transform(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 1593, in transform
    check_is_fitted(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1461, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This RobustScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
2025-01-07 01:18:32 ERROR auto_prep.preprocessing.scaling: Failed to transform ColumnScaler This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
Traceback (most recent call last):
  File "/Users/pawelp/Desktop/education/pw/automl/AutoPrep/auto_prep/preprocessing/scaling.py", line 94, in transform
    X_transformed[numerical_cols] = self.scaler.transform(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 1003, in transform
    check_is_fitted(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1461, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This StandardScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
2025-01-07 01:18:32 ERROR auto_prep.preprocessing.scaling: Failed to transform ColumnScaler This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
Traceback (most recent call last):
  File "/Users/pawelp/Desktop/education/pw/automl/AutoPrep/auto_prep/preprocessing/scaling.py", line 94, in transform
    X_transformed[numerical_cols] = self.scaler.transform(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 513, in transform
    check_is_fitted(self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/automl/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1461, in check_is_fitted
    raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
